# Site settings
title: pknopf
email: theonlylawislove@gmail.com
description: >
  A personal blog about technology and software development.
baseurl: ""
url: "http://www.pknopf.com" # the base hostname & protocol for your site

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
  - title: Categories
    url: /categories
  - title: About
    url: /about

# Build settings
markdown: kramdown
highlighter: pygments
disqus_shortname: pknopf

owner:
  name:           Paul Knopf
  twitter_username: theonlylawislov
  github_username:  theonlylawislove